### ISSUE TITLE
UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined.

### ISSUE THREAD

**Issue by adammiller1** [erickrf/autoencoder#11]
I encountered an error but not sure where the  problem is, whether my data, config, etc. Here is the error output trying to run train-autoencoder. I'd greatly appreciate any help you might provide.

Thanks!!!

C:\Users\adammil\Documents\autoencoder-master\src>python train-autoencoder.py output vocabulary.txt train-data.npz valid-data.npz
2018-07-25 13:24:33.172002: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-07-25 13:24:33.742632: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties:
name: Quadro M1200 major: 5 minor: 0 memoryClockRate(GHz): 1.148
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.35GiB
2018-07-25 13:24:33.750262: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2018-07-25 13:24:35.118646: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-25 13:24:35.123184: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0
2018-07-25 13:24:35.125820: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N
2018-07-25 13:24:35.129404: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3077 MB memory) -> physical GPU (device: 0, name: Quadro M1200, pci bus id: 0000:01:00.0, compute capability: 5.0)
INFO:root:Reading training data
INFO:root:Reading validation data
INFO:root:Creating model
WARNING:tensorflow:From C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
WARNING:tensorflow:From C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
autoencoder/embeddings:0: (30125, 300) (9037500 parameters)
autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
projection/dense/kernel:0: (1000, 30125) (30125000 parameters)
projection/dense/bias:0: (30125,) (30125 parameters)
Total: 42396625 parameters
INFO:root:Initialized the model and all variables. Starting training.
Traceback (most recent call last):
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/bw/bw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/bw/bw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
         [[Node: sampled_softmax_loss/sparse_indices/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_625_sampled_softmax_loss/sparse_indices", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train-autoencoder.py", line 113, in <module>
    args.dropout_keep, 5.0, report_interval=args.interval)
  File "C:\Users\adammil\Documents\autoencoder-master\src\autoencoder.py", line 257, in train
    _, loss = session.run([self.train_op, self.loss], feeds)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/bw/bw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/bw/bw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
         [[Node: sampled_softmax_loss/sparse_indices/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_625_sampled_softmax_loss/sparse_indices", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "C:\Users\adammil\Documents\autoencoder-master\src\autoencoder.py", line 163, in __init__
    self._create_training_tensors()
  File "C:\Users\adammil\Documents\autoencoder-master\src\autoencoder.py", line 200, in _create_training_tensors
    gradients, v = zip(*optimizer.compute_gradients(self.loss))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\optimizer.py", line 511, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 532, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 701, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 396, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 701, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_grad.py", line 186, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 873, in gather
    return self._implementation.gather(indices, name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 303, in gather
    element_shape=element_shape)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 6479, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "C:\Users\adammil\Documents\autoencoder-master\src\autoencoder.py", line 85, in __init__
    scope=self.scope)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 429, in bidirectional_dynamic_rnn
    time_major=time_major, scope=bw_scope)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 618, in dynamic_rnn
    dtype=dtype)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 745, in _dynamic_rnn_loop
    for ta, input_ in zip(input_ta, flat_input))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\rnn.py", line 745, in <genexpr>
    for ta, input_ in zip(input_ta, flat_input))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 907, in unstack
    return self._implementation.unstack(value, name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 331, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 347, in scatter
    name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 7087, in tensor_array_scatter_v3
    flow_in=flow_in, name=name)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\adammil\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/bw/bw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/bw/bw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
         [[Node: sampled_softmax_loss/sparse_indices/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_625_sampled_softmax_loss/sparse_indices", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by erickrf** [comment]
Other people have reported a similar issue, but I still haven't been able to reproduce it or find the bug. Can you post your training data, or a subset of it?

**Comment by adammiller1** [comment]
Thanks for the reply!

The issue, I believe, is dirty data, where my sentences file has some encoding problems, meaning some lines contain text that is not proper UTF8. My test data comes from our SQL server where I don't have control over the encoding or quality. 

I haven't figured out yet how to identify the offending lines of my sentences file and clean them out. To workaround, I just snipped the file down to a tenth of what it was (must have snipped around the bad lines) and now I can run all the way through the scripts and I've got my output.npy file after training and testing.

Now I am trying to understand the contents of the output.npy file so I can see what my model has learned and how to best use the output. If you have any pointers I would greatly appreciate it!

I'm very new to Tensorflow so it feels great to have gotten this far!

**Comment by adammiller1** [comment]
Just a follow-up: My problem was having empty lines in my input sentences file and some sentences that consisted of only one character. I removed empties and removed anything under 5 characters from the input sentences and got past the issue.

Wow, production data is very dirty and takes a lot of effort to clean it up to be ready for training. :)

**Comment by shivamakhauri04** [comment]
getting the same error.
@erickrf  Can you share the dataset you have used, which is not throwing any error ? May be we can compare with ours and figure out why the error is coming

**Comment by shivamakhauri04** [comment]
![screenshot from 2018-08-21 12-41-02](https://user-images.githubusercontent.com/29355854/44386249-98360580-a53f-11e8-80e2-71145b92d40c.png)


Realized that some datasets are creating 0 valid/train sizes in the differnt size bins.Also there comes a a size bin of size <0 .which causes suh error to come

**Comment by erickrf** [comment]
Good that you found the error. I should check the data preparation script to avoid the zero sized bin.
