### ISSUE TITLE
UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. 

### ISSUE THREAD

**Issue by abubakar-ucr** [erickrf/autoencoder#15]
Hi, 
I tried to run your code, while running train-autoencoder.py, I am getting the following error. Full trace is pasted below:
autoencoder/embeddings:0: (571, 300) (171300 parameters)
autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
projection/dense/kernel:0: (1000, 571) (571000 parameters)
projection/dense/bias:0: (571,) (571 parameters)
Total: 3946871 parameters
INFO:root:Initialized the model and all variables. Starting training.
Traceback (most recent call last):
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/fw/fw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/fw/fw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train-autoencoder.py", line 113, in <module>
    args.dropout_keep, 5.0, report_interval=args.interval)
  File "/Users/abubakar/Documents/chatbot/tensorflow/autoencoder/src/autoencoder.py", line 257, in train
    _, loss = session.run([self.train_op, self.loss], feeds)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/fw/fw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/fw/fw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]

Caused by op 'gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "/Users/abubakar/Documents/chatbot/tensorflow/autoencoder/src/autoencoder.py", line 163, in __init__
    self._create_training_tensors()
  File "/Users/abubakar/Documents/chatbot/tensorflow/autoencoder/src/autoencoder.py", line 200, in _create_training_tensors
    gradients, v = zip(*optimizer.compute_gradients(self.loss))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 526, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 385, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 186, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 910, in gather
    return self._implementation.gather(indices, name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6018, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "/Users/abubakar/Documents/chatbot/tensorflow/autoencoder/src/autoencoder.py", line 85, in __init__
    scope=self.scope)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 412, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 627, in dynamic_rnn
    dtype=dtype)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 754, in _dynamic_rnn_loop
    for ta, input_ in zip(input_ta, flat_input))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 754, in <genexpr>
    for ta, input_ in zip(input_ta, flat_input))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 944, in unstack
    return self._implementation.unstack(value, name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 333, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 349, in scatter
    name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6590, in tensor_array_scatter_v3
    flow_in=flow_in, name=name)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/abubakar/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/fw/fw/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/fw/fw/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]

**Comment by erickrf** [comment]
Please check the other issues. This apparently happens when one or more of the sentence bins, which group sentences by sizes 10-20, 20-30, etc, is empty. I'll try to fix it soon when I have time.

**Comment by abubakar-ucr** [comment]
Can anybody share the data for which this code works?
