### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Sampler's range is too small.

### ISSUE THREAD

**Issue by TobiasEl** [erickrf/autoencoder#18]
Hi, I'm having this problem while running (vocabulary.txt train-data.npz valid-data.npz are generated by prepare-data.py):
train-autoencoder.py output_directory vocabulary.txt train-data.npz valid-data.npz

autoencoder/embeddings:0: (23, 300) (6900 parameters)
autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
projection/dense/kernel:0: (1000, 23) (23000 parameters)
projection/dense/bias:0: (23,) (23 parameters)
Total: 3233923 parameters
INFO:root:Initialized the model and all variables. Starting training.
Traceback (most recent call last):
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Sampler's range is too small.
         [[{{node sampled_softmax_loss/LogUniformCandidateSampler}} = LogUniformCandidateSampler[num_sampled=100, num_true=1, range_max=23, seed=0, seed2=0, unique=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sampled_softmax_loss/Cast)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fanta\Desktop\autoencoder-master\src\train-autoencoder.py", line 113, in <module>
    args.dropout_keep, 5.0, report_interval=args.interval)
  File "C:\Users\fanta\Desktop\autoencoder-master\src\autoencoder.py", line 257, in train
    _, loss = session.run([self.train_op, self.loss], feeds)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Sampler's range is too small.
         [[node sampled_softmax_loss/LogUniformCandidateSampler (defined at C:\Users\fanta\Desktop\autoencoder-master\src\autoencoder.py:194)  = LogUniformCandidateSampler[num_sampled=100, num_true=1, range_max=23, seed=0, seed2=0, unique=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sampled_softmax_loss/Cast)]]

Caused by op 'sampled_softmax_loss/LogUniformCandidateSampler', defined at:
  File "C:\Users\fanta\Desktop\autoencoder-master\src\train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "C:\Users\fanta\Desktop\autoencoder-master\src\autoencoder.py", line 163, in __init__
    self._create_training_tensors()
  File "C:\Users\fanta\Desktop\autoencoder-master\src\autoencoder.py", line 194, in _create_training_tensors
    self.vocab_size)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py", line 1349, in sampled_softmax_loss
    seed=seed)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py", line 1046, in _compute_sampled_logits
    seed=seed)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\candidate_sampling_ops.py", line 145, in log_uniform_candidate_sampler
    seed2=seed2, name=name)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_candidate_sampling_ops.py", line 730, in log_uniform_candidate_sampler
    range_max=range_max, seed=seed, seed2=seed2, name=name)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Sampler's range is too small.
         [[node sampled_softmax_loss/LogUniformCandidateSampler (defined at C:\Users\fanta\Desktop\autoencoder-master\src\autoencoder.py:194)  = LogUniformCandidateSampler[num_sampled=100, num_true=1, range_max=23, seed=0, seed2=0, unique=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sampled_softmax_loss/Cast)]]

What I can do to solve this erros?
Thank you.

**Comment by erickrf** [comment]
I have never seen these errors. What version of tensorflow are you using?

**Comment by TobiasEl** [comment]
Hi.
The version is '1.12.0'

**Comment by TobiasEl** [comment]
I don't know if it's because the vocabulary.txt is so short. I only have this 23 elements:
</s>
<unk>
not
/
...
//
http:
will
www.
#
can
know
@
popular
social
#pleconsell
now
us
work
already
trump
https:
old

**Comment by TobiasEl** [comment]
I solve the problem. It was hapening because the vocabulary.txt had only 23 elements, I generate a new txt with at leats 100 words.
But I run the code:
train-autoencoder.py output_directory vocabulary.txt train-data.npz valid-data.npz

The code ends without any error and nothing hapen. Doesn't generate a directory with the model trained

**Comment by erickrf** [comment]
Did it give any more logging messages? It should save the model after evaluating in the validation data. If your dataset is too small it may not even be getting to the validation.

**Comment by TobiasEl** [comment]
Show this:

INFO:root:Reading training data
INFO:root:Reading validation data
INFO:root:Creating model
WARNING:tensorflow:From C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py:1124: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py:1124: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
autoencoder/embeddings:0: (105, 300) (31500 parameters)
autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
projection/dense/kernel:0: (1000, 105) (105000 parameters)
projection/dense/bias:0: (105,) (105 parameters)
Total: 3340605 parameters
INFO:root:Initialized the model and all variables. Starting training.

C:\Users\fanta\Desktop\autoencoder-master\src>

**Comment by erickrf** [comment]
Yes, that was the case. You need to set a smaller evaluation interval or preferably use a larger dataset.

**Comment by TobiasEl** [comment]
But I made a lot of tries, the last with 2571 parametres and continues without generating the model:
INFO:root:Reading training data
INFO:root:Reading validation data
INFO:root:Creating model
WARNING:tensorflow:From C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py:1124: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From C:\Users\fanta\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\nn_impl.py:1124: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
autoencoder/embeddings:0: (2751, 300) (825300 parameters)
autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
projection/dense/kernel:0: (1000, 2751) (2751000 parameters)
projection/dense/bias:0: (2751,) (2751 parameters)
Total: 6783051 parameters
INFO:root:Initialized the model and all variables. Starting training.

(in this point train some minutes)

C:\Users\fanta\Desktop\autoencoder-master\src>

**Comment by erickrf** [comment]
By more training data, I mean more sentences. What you mean is that you increased the vocabulary size. You should set a lower value for the evaluation interval, using the `-i` parameter. It sets how many training batches to wait before validating, and the batch size is determined by `-b`. By default, `-i` is 1000 and `-b` is 32, which means you have less than 32k training sentences. But even if you set a lower `-i`, with a dataset this size you will probably not get good results.

**Comment by calebauyang** [comment]
> By more training data, I mean more sentences. What you mean is that you increased the vocabulary size. You should set a lower value for the evaluation interval, using the `-i` parameter. It sets how many training batches to wait before validating, and the batch size is determined by `-b`. By default, `-i` is 1000 and `-b` is 32, which means you have less than 32k training sentences. But even if you set a lower `-i`, with a dataset this size you will probably not get good results.

where can i add the code '-i parameter' and '-b parameter'?  thank you!

**Comment by erickrf** [comment]
@calebauyang they are command line parameters to the script `train-autoencoder.py`
