### ISSUE TITLE
when using on raw text it is working but, on preprocessed and stemmed version of same text it does not! 

### ISSUE THREAD

**Issue by RanaBan** [erickrf/autoencoder#25]
I am a beginner in this. I applied your code to get sentence vectors, **it works well on the raw text but when using it on the preprocessed (with stemming) version of the same text it does not work. The "prepare-data" works fine and successfully supplied train_data.npz, valid_data.npz and vocabulary.txt. The next step which is the "train_autoencoder" didn't work**. Please check the error message given below
autoencoder/embeddings:0: (2845, 100) (284500 parameters)
autoencoder/fw/lstm_cell/kernel:0: (228, 512) (116736 parameters)
autoencoder/fw/lstm_cell/bias:0: (512,) (512 parameters)
autoencoder/bw/lstm_cell/kernel:0: (228, 512) (116736 parameters)
autoencoder/bw/lstm_cell/bias:0: (512,) (512 parameters)
projection/dense/kernel:0: (256, 2845) (728320 parameters)
projection/dense/bias:0: (2845,) (2845 parameters)
Total: 1250161 parameters
INFO:root:Initialized the model and all variables. Starting training.
2020-11-23 13:40:47.008677: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: 2 root error(s) found.
  (0) Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[{{node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3}}]]
	 [[truediv/_139]]
  (1) Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[{{node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/My Drive/Autoencoder/train-autoencoder.py", line 117, in <module>
    args.dropout_keep, 5.0, report_interval=args.interval)
  File "/content/drive/My Drive/Autoencoder/autoencoder.py", line 259, in train
    _, loss = session.run([self.train_op, self.loss], feeds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: 2 root error(s) found.
  (0) Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 (defined at content/drive/My Drive/Autoencoder/autoencoder.py:202) ]]
	 [[truediv/_139]]
  (1) Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 (defined at content/drive/My Drive/Autoencoder/autoencoder.py:202) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3:
 autoencoder/autoencoder/fw/fw/TensorArrayUnstack/range (defined at content/drive/My Drive/Autoencoder/autoencoder.py:87)

Input Source operations connected to node gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3:
 autoencoder/autoencoder/fw/fw/TensorArrayUnstack/range (defined at content/drive/My Drive/Autoencoder/autoencoder.py:87)

Original stack trace for 'gradients/autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3':
  File "content/drive/My Drive/Autoencoder/train-autoencoder.py", line 110, in <module>
    bidirectional=args.bidirectional)
  File "content/drive/My Drive/Autoencoder/autoencoder.py", line 165, in __init__
    self._create_training_tensors()
  File "content/drive/My Drive/Autoencoder/autoencoder.py", line 202, in _create_training_tensors
    gradients, v = zip(*optimizer.compute_gradients(self.loss))
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py", line 172, in gradients
    unconnected_gradients)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_grad.py", line 204, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 1190, in gather
    return self._implementation.gather(indices, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6481, in tensor_array_gather_v3
    element_shape=element_shape, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'autoencoder/autoencoder/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "content/drive/My Drive/Autoencoder/train-autoencoder.py", line 110, in <module>
    bidirectional=args.bidirectional)
  File "content/drive/My Drive/Autoencoder/autoencoder.py", line 87, in __init__
    scope=self.scope)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 447, in bidirectional_dynamic_rnn
    scope=fw_scope)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 691, in dynamic_rnn
    dtype=dtype)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 823, in _dynamic_rnn_loop
    ta.unstack(input_) for ta, input_ in zip(input_ta, flat_input))
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py", line 823, in <genexpr>
    ta.unstack(input_) for ta, input_ in zip(input_ta, flat_input))
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 1224, in unstack
    return self._implementation.unstack(value, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 328, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),

**Comment by RanaBan** [comment]
I just found that a sentence becoming 0 length after preprocessing.
