### ISSUE TITLE
Model initialisation problem

### ISSUE THREAD

**Issue by akbari59** [erickrf/autoencoder#3]
I have tried to run your code but I got the following exception: 

```
INFO:root:Reading training data
INFO:root:Reading validation data
INFO:root:Creating model
Traceback (most recent call last):
  File "/Users/i342044/virtualenv-dir/py3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 578, in as_dtype
    if key == type_value:
TypeError: data type not understood

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/i342044/Documents/Codes/autoencoder-master/src/train-autoencoder.py", line 113, in <module>
    bidirectional=args.bidirectional)
  File "/Users/i342044/Documents/Codes/autoencoder-master/src/autoencoder.py", line 84, in __init__
    initializer = tf.zeros_initializer((self.vocab_size,))
  File "/Users/i342044/virtualenv-dir/py3/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 88, in __init__
    self.dtype = dtypes.as_dtype(dtype)
  File "/Users/i342044/virtualenv-dir/py3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 581, in as_dtype
    raise TypeError("Cannot convert {} to a dtype. {}".format(type_value, e))
TypeError: Cannot convert (4477,) to a dtype. data type not understood

Process finished with exit code 1
```
Any idea on how to solve it?

Thanks

**Comment by erickrf** [comment]
This happens because of some API changes recent Tensorflow versions. 

To be honest, I don't plan to update this project anymore. You can try running the Tensorflow migration script, but I found that it doesn't always make all the necessary changes, or else downgrade to Tensorflow 0.12.
